# Generated by Django 4.2.3 on 2026-06-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_submission_question_choice_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.CharField(default='content', max_length=200),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='total_learners',
            field=models.IntegerField(default=0),
        ),
    ]
